from __future__ import annotations

OPENCODE_GO_CHAT_PROVIDER_ID = "opencode-go-chat-completions"
OPENCODE_GO_PROVIDER_SYSTEM = "opencode-go"
OPENCODE_GO_BASE_URL = "https://opencode.ai/zen/go/v1"
OPENCODE_GO_SEMANTIC_MODELS = frozenset({"deepseek-v4-flash"})
OPENCODE_GO_SEMANTIC_MAX_OUTPUT_TOKENS = 240
OPENCODE_GO_SEMANTIC_TIMEOUT_SECONDS = 60.0
OPENCODE_GO_SEMANTIC_API_FAMILY = "chat-completions"
OPENCODE_GO_SEMANTIC_TASK = "support-semantic-v7"
OPENCODE_GO_SEMANTIC_PRIVACY_POLICY = "current-request-text-only-v1"
OPENCODE_GO_SEMANTIC_BUDGET_PROFILE = "single-call-60s-240-v1"
OPENCODE_GO_SEMANTIC_EVALUATION = "opencode-go-forward-heldout-40-20260815-v7-prompt-v5-zh-e"
OPENCODE_GO_BUG_ASSESSMENT_TASK = "bug-assessment-agent-v1"
OPENCODE_GO_BUG_ASSESSMENT_PRIVACY_POLICY = "bounded-visible-conversation-source-log-design-v1"
OPENCODE_GO_BUG_ASSESSMENT_BUDGET_PROFILE = (
    "agent-9req-1conversation-plus-6evidence-tool-output-correction-120k-0.50usd-v3"
)
OPENCODE_GO_BUG_ASSESSMENT_EVALUATION = (
    "opencode-go-bug-forward-heldout-16-20260815-v1-prompt-v8-zh-d"
)
OPENCODE_GO_BUG_ASSESSMENT_TIMEOUT_SECONDS = 120.0
OPENCODE_GO_BUG_ASSESSMENT_MAX_OUTPUT_TOKENS = 800

__all__ = (
    "OPENCODE_GO_BASE_URL",
    "OPENCODE_GO_BUG_ASSESSMENT_BUDGET_PROFILE",
    "OPENCODE_GO_BUG_ASSESSMENT_EVALUATION",
    "OPENCODE_GO_BUG_ASSESSMENT_MAX_OUTPUT_TOKENS",
    "OPENCODE_GO_BUG_ASSESSMENT_PRIVACY_POLICY",
    "OPENCODE_GO_BUG_ASSESSMENT_TASK",
    "OPENCODE_GO_BUG_ASSESSMENT_TIMEOUT_SECONDS",
    "OPENCODE_GO_CHAT_PROVIDER_ID",
    "OPENCODE_GO_PROVIDER_SYSTEM",
    "OPENCODE_GO_SEMANTIC_API_FAMILY",
    "OPENCODE_GO_SEMANTIC_BUDGET_PROFILE",
    "OPENCODE_GO_SEMANTIC_EVALUATION",
    "OPENCODE_GO_SEMANTIC_MAX_OUTPUT_TOKENS",
    "OPENCODE_GO_SEMANTIC_MODELS",
    "OPENCODE_GO_SEMANTIC_PRIVACY_POLICY",
    "OPENCODE_GO_SEMANTIC_TASK",
    "OPENCODE_GO_SEMANTIC_TIMEOUT_SECONDS",
)
