"""initial bug workflow

迁移 ID: edc3fe0967f9
父迁移:
创建时间: 2026-08-16 00:35:52.111623

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "edc3fe0967f9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_triage",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_triage_bug_problem",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("public_id", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("subject_id", sa.String(length=256), nullable=False),
        sa.Column("adapter_name", sa.String(length=128), nullable=False),
        sa.Column("signature_kind", sa.String(length=32), nullable=True),
        sa.Column("signature_revision", sa.String(length=64), nullable=True),
        sa.Column("signature_digest", sa.String(length=64), nullable=True),
        sa.Column("current_verdict", sa.String(length=16), nullable=False),
        sa.Column("decision_source", sa.String(length=32), nullable=False),
        sa.Column("review_status", sa.String(length=16), nullable=False),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.Column("responsibility_candidates", sa.JSON(), nullable=False),
        sa.Column("first_observed_at", sa.String(length=40), nullable=False),
        sa.Column("last_observed_at", sa.String(length=40), nullable=False),
        sa.Column("current_decision_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_triage_bug_problem")),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint(
            "signature_kind",
            "signature_revision",
            "signature_digest",
            name="uq_nonebot_plugin_triage_bug_problem_signature",
        ),
        info={"bind_key": "nonebot_plugin_triage"},
    )
    with op.batch_alter_table("nonebot_plugin_triage_bug_problem", schema=None) as batch_op:
        batch_op.create_index(
            "ix_nonebot_plugin_triage_bug_problem_pending",
            ["current_verdict", "lifecycle", "last_observed_at"],
            unique=False,
        )

    op.create_table(
        "nonebot_plugin_triage_bug_occurrence",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("problem_id", sa.String(length=32), nullable=False),
        sa.Column("occurrence_key", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.String(length=40), nullable=False),
        sa.Column("subject_id", sa.String(length=256), nullable=False),
        sa.Column("adapter_name", sa.String(length=128), nullable=False),
        sa.Column("correlation_digest", sa.String(length=64), nullable=True),
        sa.Column("failure_signature", sa.String(length=64), nullable=True),
        sa.Column("source_revision", sa.String(length=256), nullable=True),
        sa.Column("contract_revision", sa.String(length=256), nullable=True),
        sa.Column("deployment_generation", sa.String(length=256), nullable=True),
        sa.Column("evidence_receipts", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["nonebot_plugin_triage_bug_problem.id"],
            name=op.f(
                "fk_nonebot_plugin_triage_bug_occurrence_problem_id_nonebot_plugin_triage_bug_problem"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_triage_bug_occurrence")),
        sa.UniqueConstraint("occurrence_key"),
        info={"bind_key": "nonebot_plugin_triage"},
    )
    with op.batch_alter_table("nonebot_plugin_triage_bug_occurrence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_nonebot_plugin_triage_bug_occurrence_problem",
            ["problem_id", "observed_at"],
            unique=False,
        )

    op.create_table(
        "nonebot_plugin_triage_problem_decision",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("problem_id", sa.String(length=32), nullable=False),
        sa.Column("previous_decision_id", sa.String(length=32), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("task", sa.String(length=128), nullable=True),
        sa.Column("evaluation", sa.String(length=256), nullable=True),
        sa.Column("human_actor_hmac", sa.String(length=64), nullable=True),
        sa.Column("evidence_receipts", sa.JSON(), nullable=False),
        sa.Column("assessment_revision", sa.String(length=256), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["nonebot_plugin_triage_bug_problem.id"],
            name=op.f(
                "fk_nonebot_plugin_triage_problem_decision_problem_id_nonebot_plugin_triage_bug_problem"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_triage_problem_decision")),
        sa.UniqueConstraint("idempotency_key"),
        info={"bind_key": "nonebot_plugin_triage"},
    )
    with op.batch_alter_table("nonebot_plugin_triage_problem_decision", schema=None) as batch_op:
        batch_op.create_index(
            "ix_nonebot_plugin_triage_problem_decision_problem",
            ["problem_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "nonebot_plugin_triage_bug_report",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("report_key", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.String(length=40), nullable=False),
        sa.Column("actor_scope_hmac", sa.String(length=64), nullable=True),
        sa.Column("terminal_type", sa.String(length=16), nullable=False),
        sa.Column("occurrence_id", sa.String(length=32), nullable=False),
        sa.Column("problem_id", sa.String(length=32), nullable=False),
        sa.Column("linked_existing", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["nonebot_plugin_triage_bug_occurrence.id"],
            name=op.f(
                "fk_nonebot_plugin_triage_bug_report_occurrence_id_nonebot_plugin_triage_bug_occurrence"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["nonebot_plugin_triage_bug_problem.id"],
            name=op.f(
                "fk_nonebot_plugin_triage_bug_report_problem_id_nonebot_plugin_triage_bug_problem"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_triage_bug_report")),
        sa.UniqueConstraint("report_key"),
        info={"bind_key": "nonebot_plugin_triage"},
    )
    with op.batch_alter_table("nonebot_plugin_triage_bug_report", schema=None) as batch_op:
        batch_op.create_index(
            "ix_nonebot_plugin_triage_bug_report_problem",
            ["problem_id", "received_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_triage_bug_report", schema=None) as batch_op:
        batch_op.drop_index("ix_nonebot_plugin_triage_bug_report_problem")

    op.drop_table("nonebot_plugin_triage_bug_report")
    with op.batch_alter_table("nonebot_plugin_triage_problem_decision", schema=None) as batch_op:
        batch_op.drop_index("ix_nonebot_plugin_triage_problem_decision_problem")

    op.drop_table("nonebot_plugin_triage_problem_decision")
    with op.batch_alter_table("nonebot_plugin_triage_bug_occurrence", schema=None) as batch_op:
        batch_op.drop_index("ix_nonebot_plugin_triage_bug_occurrence_problem")

    op.drop_table("nonebot_plugin_triage_bug_occurrence")
    with op.batch_alter_table("nonebot_plugin_triage_bug_problem", schema=None) as batch_op:
        batch_op.drop_index("ix_nonebot_plugin_triage_bug_problem_pending")

    op.drop_table("nonebot_plugin_triage_bug_problem")
    # ### end Alembic commands ###
