TRIAGE_COMMAND = "triage"
QUERY_COMMAND = "报错查询"
TRIAGE_MATCHER_PRIORITY = 10
MAINTAINER_MATCHER_PRIORITY = 10
TEACHING_REFRESH_MATCHER_PRIORITY = 9
TRIAGE_REQUEST_MAX_CHARS = 2_000

__all__ = (
    "MAINTAINER_MATCHER_PRIORITY",
    "QUERY_COMMAND",
    "TEACHING_REFRESH_MATCHER_PRIORITY",
    "TRIAGE_COMMAND",
    "TRIAGE_MATCHER_PRIORITY",
    "TRIAGE_REQUEST_MAX_CHARS",
)
