TRIAGE_COMMAND = "triage"
QUERY_COMMAND = "报错查询"
FEEDBACK_COMMAND = "报错反馈"
TRIAL_STATS_COMMAND = "报错统计"
TRIAGE_MATCHER_PRIORITY = 10
MAINTAINER_MATCHER_PRIORITY = 10
TRIAGE_REQUEST_MAX_CHARS = 2_000

__all__ = (
    "FEEDBACK_COMMAND",
    "MAINTAINER_MATCHER_PRIORITY",
    "QUERY_COMMAND",
    "TRIAGE_COMMAND",
    "TRIAGE_MATCHER_PRIORITY",
    "TRIAGE_REQUEST_MAX_CHARS",
    "TRIAL_STATS_COMMAND",
)
